#!/usr/bin/env bash

# add next line to your .bashrc
# [ -f $HOME/.myrc ] && source $HOME/.myrc

# Default to human readable figures
alias df='df -h'
alias du='du -h'
#
# Misc :)
alias less='less -r'             # raw control characters
alias grep='grep --color'        # show differences in colour
alias egrep='egrep --color=auto' # show differences in colour
alias fgrep='fgrep --color=auto' # show differences in colour
alias ls='ls --color=auto -h'
alias ll='ls -l'
alias gitd='git difftool'
alias rlf='readlink -f'
alias cls='clear'

# PS1='[\u@\h \W]\$ '
export EDITOR=vim
LANG=zh_CN.UTF-8
# vim 中打开文件取消注释下面行
# export LANG=C.UTF-8

proxyon() {
    export http_proxy="http://IP:PORT"
    export https_proxy="http://IP:PORT"
}

proxyoff() {
    unset http_proxy
    unset https_proxy
}

# Set PATH so it includes user's private bin if it exists
if [ -d "${HOME}/.bin" ]; then
    PATH="${HOME}/.bin:${PATH}"
fi

if [ -d "$HOME/.local/bin" ] ; then
        PATH="$HOME/.local/bin:${PATH}"
fi

if [ -d "$HOME/.local/lib" ] ; then
        export LD_LIBRARY_PATH="$HOME/.local/lib:${LD_LIBRARY_PATH}"
fi

if [[ -n "${BASH_VERSION}" ]]; then
    PROMPT_COMMAND=__prompt_command
fi

# shell命令行中执行完命令之后，如果非正常退出，显示状态码
__prompt_command() {
    local EXIT="$?"
    local str="exit code "
    if [ $EXIT != 0 ]; then
        echo "$(tput setaf 1)"${str}$EXIT"$(tput sgr0)"
    fi
}

if [ "$(command -v xdg-open)" ]; then
    alias start="xdg-open"
fi

# bash上下键匹配历史
if [[ $- == *i* ]]; then
    bind '"\e[A": history-search-backward'
    bind '"\e[B": history-search-forward'
fi